"""baseline: capture existing schema

Revision ID: d27f51392651
Revises: 
Create Date: 2026-03-25 21:15:21.177094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27f51392651'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('address1', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('zip_code', sa.String(length=16), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_partner', sa.Boolean(), nullable=False),
    sa.Column('rent_amount', sa.Float(), nullable=True),
    sa.Column('rent_frequency', sa.String(length=16), nullable=True),
    sa.Column('contact_name', sa.String(length=256), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_email', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('picture', sa.String(length=512), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('agent_carrier_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('carrier', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('split_rate', sa.Float(), nullable=False),
    sa.Column('id_type', sa.String(length=32), nullable=True),
    sa.Column('id_value', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'carrier', name='uq_agent_carrier')
    )
    with op.batch_alter_table('agent_carrier_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_carrier_contracts_agent_id'), ['agent_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commission_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrier', sa.String(length=64), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('period_label', sa.String(length=32), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('gross_amount', sa.Float(), nullable=True),
    sa.Column('bonus_amount', sa.Float(), nullable=True),
    sa.Column('split_rate', sa.Float(), nullable=True),
    sa.Column('expected_amount', sa.Float(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('difference', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('line_items', sa.Text(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrier', 'agent_id', 'period_label', name='uq_commission_period')
    )
    with op.batch_alter_table('commission_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_statements_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_statements_carrier'), ['carrier'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mbi', sa.String(length=20), nullable=True),
    sa.Column('humana_id', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('phone_primary', sa.String(length=32), nullable=True),
    sa.Column('phone_secondary', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('address1', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('zip_code', sa.String(length=16), nullable=True),
    sa.Column('county', sa.String(length=128), nullable=True),
    sa.Column('carrier_address', sa.String(length=512), nullable=True),
    sa.Column('medicaid_level', sa.String(length=32), nullable=True),
    sa.Column('medicaid_id', sa.String(length=64), nullable=True),
    sa.Column('deal_stage', sa.String(length=32), nullable=True),
    sa.Column('lead_source', sa.String(length=64), nullable=True),
    sa.Column('primary_agent_id', sa.Integer(), nullable=True),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.Column('manually_edited', sa.Boolean(), nullable=False),
    sa.Column('last_carrier_sync', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['primary_agent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_dob'), ['dob'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_humana_id'), ['humana_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_mbi'), ['mbi'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_phone_primary'), ['phone_primary'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_primary_agent_id'), ['primary_agent_id'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrier', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('new_count', sa.Integer(), nullable=True),
    sa.Column('updated_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_aor_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('carrier', sa.String(length=64), nullable=True),
    sa.Column('plan_name', sa.String(length=256), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'carrier', 'effective_date', name='uq_aor_customer_carrier_date')
    )
    with op.batch_alter_table('customer_aor_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_aor_history_customer_id'), ['customer_id'], unique=False)

    op.create_table('customer_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=256), nullable=False),
    sa.Column('relationship', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_contacts_customer_id'), ['customer_id'], unique=False)

    op.create_table('customer_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=True),
    sa.Column('note_type', sa.String(length=32), nullable=True),
    sa.Column('contact_method', sa.String(length=32), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('openphone_call_id', sa.String(length=128), nullable=True),
    sa.Column('calendly_event_id', sa.String(length=128), nullable=True),
    sa.Column('fireflies_meeting_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_notes_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_notes_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_notes_note_type'), ['note_type'], unique=False)

    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrier', sa.String(length=64), nullable=False),
    sa.Column('member_id', sa.String(length=128), nullable=False),
    sa.Column('mbi', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=256), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address1', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('zip_code', sa.String(length=16), nullable=True),
    sa.Column('county', sa.String(length=128), nullable=True),
    sa.Column('plan_name', sa.String(length=256), nullable=True),
    sa.Column('plan_type', sa.String(length=64), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('term_date', sa.Date(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('agent_id_carrier', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('last_seen_date', sa.Date(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('zoho_matched', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrier', 'member_id', name='uq_carrier_member')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_carrier'), ['carrier'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_mbi'), ['mbi'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_member_id'), ['member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_member_id'))
        batch_op.drop_index(batch_op.f('ix_policies_mbi'))
        batch_op.drop_index(batch_op.f('ix_policies_carrier'))
        batch_op.drop_index(batch_op.f('ix_policies_agent_id'))

    op.drop_table('policies')
    with op.batch_alter_table('customer_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_notes_note_type'))
        batch_op.drop_index(batch_op.f('ix_customer_notes_customer_id'))
        batch_op.drop_index(batch_op.f('ix_customer_notes_created_at'))
        batch_op.drop_index(batch_op.f('ix_customer_notes_agent_id'))

    op.drop_table('customer_notes')
    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_contacts_customer_id'))

    op.drop_table('customer_contacts')
    with op.batch_alter_table('customer_aor_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_aor_history_customer_id'))

    op.drop_table('customer_aor_history')
    op.drop_table('import_batches')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_primary_agent_id'))
        batch_op.drop_index(batch_op.f('ix_customers_phone_primary'))
        batch_op.drop_index(batch_op.f('ix_customers_mbi'))
        batch_op.drop_index(batch_op.f('ix_customers_humana_id'))
        batch_op.drop_index(batch_op.f('ix_customers_full_name'))
        batch_op.drop_index(batch_op.f('ix_customers_dob'))

    op.drop_table('customers')
    with op.batch_alter_table('commission_statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_statements_carrier'))
        batch_op.drop_index(batch_op.f('ix_commission_statements_agent_id'))

    op.drop_table('commission_statements')
    op.drop_table('audit_logs')
    with op.batch_alter_table('agent_carrier_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_carrier_contracts_agent_id'))

    op.drop_table('agent_carrier_contracts')
    op.drop_table('users')
    op.drop_table('pharmacies')
    # ### end Alembic commands ###
